### PR TITLE
Remove global ROOT_NODES/EDGES (merge after #86)

### PR DESCRIPTION
**Pull request by qinsoon**
This PR is based on https://github.com/mmtk/mmtk-julia/pull/86.
* Move stack scanning code to Rust, and implement `Scanning::scan_roots_in_mutator_thread`. 
  * Implement necessary types/functions in Rust. 
  * It is not necessary to implement this in Rust. However, it needs to use `scan_gcstack()`, which is implemented in Rust, and used for object scanning. It would be better to remove our implementation for it in C.
* Create `scan_vm_specific_roots`, and call it in `Scanning::scan_vm_specific_roots`.
  * Allow using `RootsWorkFactory` in C
* Remove global `ROOT_NODES/EDGES` as they are no longer used.
* Add assertions to check type size for our Rust and C types.

### CODE REVIEW

**Review by udesou — APPROVED** [review]
It looks good to me. This might require a few changes to support moving immix (tpinned roots), but I believe these changes introduced here aren't gonna impact on supporting tpinned roots.

**Comment by udesou** [comment]
Does this impact performance in any way? Have you tested it with the previous benchmarks? I'm just wondering whether it would help at least a bit since it removes those locks.

**Comment by qinsoon** [comment]
> Does this impact performance in any way? Have you tested it with the previous benchmarks? I'm just wondering whether it would help at least a bit since it removes those locks.

I haven't tested that. It should improve the stack scanning. But I am not sure how much it matters for the whole GC time. I see this PR as a cleanup rather than an optimization. But anyway, I will run the benchmarks.

**Comment by qinsoon** [comment]
This is the result (compared with Julia GC). It seems we only see a clear improvement in `pidigits`. I think the reason is that stack scanning is a fixed cost per GC and we trigger much more GCs in `pidigits` than other benchmarks. So the improvement is only visible for `pidigits`.
output

**Pull request merged**
